### ISSUE TITLE
Please make sure you have the correct access rights

### ISSUE THREAD

**Issue by JpUsefRye** [hazbo/httpu#4]
![err](https://user-images.githubusercontent.com/23387530/42419337-4d42665a-82bb-11e8-9ce0-eaeaa961a585.png)

Linux 4.17.2-1-ARCH x86_64
go version go1.10.3 linux/amd64

**Comment by hazbo** [comment]
In the meantime, a quick workaround for what that command is basically doing would be:
```
mkdir -p ~/.httpu/packages
git clone git@github.com:httpu/packages.git ~/.httpu/packages
```
If you could run those and let me know if all is good, it'd be much appreciated. Just to further clarify what is happening here, httpu is pulling down "packages", which are basically pre-configured setups to work with various HTTP APIs. https://github.com/httpu/packages
