### ISSUE TITLE
Can't rebuild packages

### ISSUE THREAD

**Issue by AdvancedHacker101** [hazbo/httpu#6]
Hi!
I cloned, the project, it works, but when I modify the code in for ex. `cmd/httpu/commands/new.go`  
then do `make build` after that, it seems like nothing has changed!!  
I also tried a lot of other things including `make clean && make build` `make install` `go install ./...`
but none of the above did the trick.  
However when changing code in `cmd/httpu/main.go`, then building the project works.  
My go version output `go version go1.10 linux/amd64`

**Comment by hazbo** [comment]
Hey there, sorry that's my bad, I think I've messed up the make file.
This is what I've been doing:
```
make clean
make
./build/httpu
```
Let me know if that works! 😄

**Comment by AdvancedHacker101** [comment]
No, it didn't work for me :(

**Comment by hazbo** [comment]
Hmmm, that's strange. You could maybe try:
```
cd cmd/httpu
go build
```

**Comment by AdvancedHacker101** [comment]
No success :(  
I'm running this on WSL if that could be problem, also on a mounted drive from windows.

**Comment by AdvancedHacker101** [comment]
Yes, exactly, running`make clean` removes the httpu binary from the `build/`, and `make` compiles the binary and places it in `build/`, but only changes made to `cmd/httpu/main.go` are compiled into the binary.

**Comment by hazbo** [comment]
Maybe something to do with the pkg cache?
You could try `rm -rf $GOPATH/pkg/OS_ARCH/github.com/hazbo/httpu`

`OS_ARCH` being which ever directory exists there (`ls $GOPATH/pkg`)

**Comment by AdvancedHacker101** [comment]
No, this didn't help, I can comfirm that the same issue is present on my Kali VM, on a non-mounted filesystem if that helps

**Comment by hazbo** [comment]
And the project exists within `$GOPATH/src/github.com/hazbo/httpu` ?

**Comment by AdvancedHacker101** [comment]
Yes, that's correct

**Comment by hazbo** [comment]
Well I'm officially all out of ideas. If you'd like to jump on a hangout call or something at one point, I'd be happy to help you figure this one out. I am curious about this issue myself. Just unable to regenerate.

**Comment by AdvancedHacker101** [comment]
OK, I got something, I tried to look for other `new.go` files on the system with `find`, and I found a second file under `vendor/github.com/hazbo/httpu/cmd/httpu/commands/new.go`, changing the file there, then running `make clean`, then running `make`, did build the binary, and the binary had the changes from the file.  
I'm not too familiar with the `go` build/get system so if this helps you could, you describe why is this working the way it does, like there's another copy of the project under `vendor/` ???  
I'm just confused, this is my first go experience.  
Then we could for sure close this issue :)

**Comment by hazbo** [comment]
Ahhhh, I didn't realise why `httpu` was in the vendor, I'm going to have to delete that. Try `rm -rf vendor/github.com/hazbo` and you should be all good!

**Comment by AdvancedHacker101** [comment]
Yes, I can confirm the above works!

**Comment by hazbo** [comment]
Excellent, feel free to commit / PR that if you like, then we can close this issue.

**Comment by AdvancedHacker101** [comment]
Ok, just give me some time, I'm also new to PRs and stuff, I just used to push to my own projects directly :)

**Comment by hazbo** [comment]
Not a problem, just make sure the only change is that deletion, push that to a branch of your fork, then you can use the GitHub user interface to create a pull request. Simple 😄
